### ISSUE TITLE
v1.4 试用版  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 13229896070** [Juszoe/flexget-nexusphp#56]
SyntaxError: invalid syntax
1. ubuntu 18.04.1  /  20.04
2.Python 3.6.9 / 3.7  /  3.8.1  /   2.7  /  
3.pip Version: 21.0
4.flexget -V 3.1.102
5.nexusphp v1.4   x
6.nexusphp v1.3   ✓ 可用

错误 代码
> flexget --test execute

> 2021-01-30 21:03:05 INFO     manager                       Test mode, creating a copy from database ...

> 2021-01-30 21:03:05 CRITICAL plugin                        Exception while loading plugin flexget.plugins.nexusphp
Traceback (most recent call last):

>   File "/usr/local/bin/flexget", line 8, in <module>

 >    sys.exit(main())
    |   |    -> <function main at 0x7f0edb112b00>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>
  File "/usr/local/lib/python3.7/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    |       -> <function Manager.start at 0x7f0ed46ba680>
    -> <flexget.manager.Manager object at 0x7f0ed77ae410>
  File "/usr/local/lib/python3.7/site-packages/flexget/manager.py", line 383, in start
    self.initialize()
    |    -> <function Manager.initialize at 0x7f0ed46ba440>
    -> <flexget.manager.Manager object at 0x7f0ed77ae410>
  File "/usr/local/lib/python3.7/site-packages/flexget/manager.py", line 225, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
                      |  |    |    |    -> '/root/.config/flexget'
                      |  |    |    -> <flexget.manager.Manager object at 0x7f0ed77ae410>
                      |  |    -> <function join at 0x7f0edc6cf170>
                      |  -> <module 'posixpath' from '/usr/local/lib/python3.7/posixpath.py'>
                      -> <module 'os' from '/usr/local/lib/python3.7/os.py'>
  File "/usr/local/lib/python3.7/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    |                       -> ['/root/.config/flexget/plugins', '/usr/local/lib/python3.7/site-packages/flexget/plugins']
    -> <function _load_plugins_from_dirs at 0x7f0ed75215f0>
  File "/usr/local/lib/python3.7/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    |              |            -> PosixPath('/root/.config/flexget/plugins/nexusphp.py')
    |              -> 'flexget.plugins.nexusphp'
    -> <function _import_plugin at 0x7f0ed75189e0>
> File "/usr/local/lib/python3.7/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    |             -> 'flexget.plugins.nexusphp'
    -> <function import_module at 0x7f0edc667ef0>
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           |          |           |    |        |        -> 0
           |          |           |    |        -> None
           |          |           |    -> 0
           |          |           -> 'flexget.plugins.nexusphp'
           |          -> <function _gcd_import at 0x7f0edc7a2b00>
           -> <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

>   File "/root/.config/flexget/plugins/nexusphp.py", line 242
    elif text in ['可连�?, '可連接', '公网']:
                            ^

> SyntaxError: invalid syntax

> Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
  File "/usr/local/lib/python3.7/site-packages/flexget/manager.py", line 383, in start
    self.initialize()
  File "/usr/local/lib/python3.7/site-packages/flexget/manager.py", line 225, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
  File "/usr/local/lib/python3.7/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
  File "/usr/local/lib/python3.7/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
  File "/usr/local/lib/python3.7/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.config/flexget/plugins/nexusphp.py", line 242
    elif text in ['可连�?, '可連接', '公网']:
                            ^

> SyntaxError: invalid syntax

**Comment by 13229896070** [comment]
nexusphp.py       原来是下了这个就会乱码
 Source code (tar.gz)    ✓ 可用
新手不好意思
