### ISSUE TITLE
OpenCD站执行出错

### ISSUE THREAD

**Issue by layefe2315** [Juszoe/flexget-nexusphp#9]
crash report内容如下：
2019-09-16 12:41 VERBOSE  input_cache   OpenCD          Restored entries from cache
2019-09-16 12:41 WARNING  details       OpenCD          Task didn't produce any entries. This is likely due to a mis-configured or non-functional input.
2019-09-16 12:41 CRITICAL task          OpenCD          BUG: Unhandled error in plugin nexusphp: 0 is out of bounds
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\flexget\task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Administrator\flexget\plugins\nexusphp.py", line 113, in on_task_filter
    task.requests.get(task.entries[0].get('link'), headers=headers)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\flexget\task.py", line 118, in __getitem__
    raise IndexError('%d is out of bounds' % item)
IndexError: 0 is out of bounds

**Comment by Juszoe** [comment]
感谢反馈，发布版已修复
